FROM python:3.12.0rc2

ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR /app

# Install dependencies:
COPY requirements.txt .
RUN pip install -r requirements.txt

# copy sources & tests
COPY src/ ./src/
COPY tests/ ./tests/

# Run the application:
CMD ["python", "src/hangman/hangman.py"]
