name: Python application

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t tink-ab-hw5 -f ./docker/Dockerfile .

      - name: Run tests
        run: docker run -t tink-ab-hw5 pytest --cov
