version: "3.8"

services:
  db:
    image: postgres:13.3
    container_name: "postgres-db"
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
    ports:
      - "15432:5432"
    restart: always
    env_file:
      - .env
    networks:
      - postgres-network

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: "pgadmin"
    ports:
      - "15433:80"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - postgres-network
    volumes:
      - ./pgadmin-data/:/var/lib/pgadmin/

networks:
  postgres-network:
    driver: bridge

volumes:
  pgdata:
  pgadmin-data:
